version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do contêiner para a 8080 do host
    depends_on:
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:mongodb://mongo:27017/meubanco  # Configura a URL do banco de dados

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Porta padrão do MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
